import type { CardDef } from "./types";

// 15 unique cards. Starting deck duplicates 4 of them.
export const CARDS: Record<string, CardDef> = {
  laser_shot: {
    id: "laser_shot",
    name: "激光射击",
    cost: 1,
    type: "attack",
    target: "enemy",
    description: "造成 6 点伤害。",
    art: "cards/laser_shot.png",
    effect: { damage: 6 },
  },
  energy_shield: {
    id: "energy_shield",
    name: "能量护盾",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 5 点格挡。",
    art: "cards/energy_shield.png",
    effect: { block: 5 },
  },
  tactical_retreat: {
    id: "tactical_retreat",
    name: "战术撤离",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 8 点格挡,抽 1 张牌。",
    art: "cards/tactical_retreat.png",
    effect: { block: 8, draw: 1 },
  },
  emergency_repair: {
    id: "emergency_repair",
    name: "应急维修",
    cost: 0,
    type: "skill",
    target: "self",
    description: "失去 2 点 HP,获得 3 点充能。",
    art: "cards/emergency_repair.png",
    effect: { hpCost: 2, charge: 3 },
  },
  med_bay: {
    id: "med_bay",
    name: "医疗舱",
    cost: 1,
    type: "skill",
    target: "self",
    description: "治疗 12 点 HP,抽 1 张牌。",
    art: "cards/med_bay.png",
    effect: { heal: 12, draw: 1 },
  },
  blood_fuel: {
    id: "blood_fuel",
    name: "血液燃料",
    cost: 0,
    type: "skill",
    target: "self",
    description: "失去 3 点 HP,本回合获得 1 点能量。",
    art: "cards/blood_fuel.png",
    effect: { hpCost: 3, bonusEnergy: 1 },
  },
  bio_link: {
    id: "bio_link",
    name: "生命链接",
    cost: 1,
    type: "skill",
    target: "self",
    description: "失去 5 点 HP,你的下一张攻击牌伤害翻倍。",
    art: "cards/bio_link.png",
    effect: { hpCost: 5, doubleNextAttack: true },
  },
  reactor_overclock: {
    id: "reactor_overclock",
    name: "反应堆超频",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。每回合开始获得 2 点充能,失去 2 HP。",
    art: "cards/reactor_overclock.png",
    effect: { custom: "reactor_overclock" },
  },
  tactical_ai: {
    id: "tactical_ai",
    name: "战术 AI",
    cost: 1,
    type: "power",
    target: "self",
    description: "能力。每当你获得充能时,获得 1 点格挡。",
    art: "cards/tactical_ai.png",
    effect: { custom: "tactical_ai" },
  },
  nano_repair: {
    id: "nano_repair",
    name: "纳米修复",
    cost: 1,
    type: "power",
    target: "self",
    description: "能力。回合结束治疗 1 HP。",
    art: "cards/nano_repair.png",
    effect: { custom: "nano_repair" },
  },
  data_scan: {
    id: "data_scan",
    name: "数据扫描",
    cost: 1,
    type: "skill",
    target: "self",
    description: "抽 2 张牌;若充能 ≥ 10,改为抽 3 张。",
    art: "cards/data_scan.png",
    effect: { custom: "data_scan" },
  },
  weakness_analysis: {
    id: "weakness_analysis",
    name: "弱点分析",
    cost: 0,
    type: "skill",
    target: "enemy",
    description: "施加 2 层易伤。",
    art: "cards/weakness_analysis.png",
    effect: { vulnerable: 2 },
  },
  plasma_strike: {
    id: "plasma_strike",
    name: "等离子斩",
    cost: 1,
    type: "attack",
    target: "enemy",
    description: "造成 8 点伤害。消耗 3 充能,则额外造成 8 点伤害。",
    art: "cards/plasma_strike.png",
    effect: { custom: "plasma_strike" },
  },
  orbital_cannon: {
    id: "orbital_cannon",
    name: "轨道炮",
    cost: 3,
    type: "attack",
    target: "enemy",
    description: "造成等同于「充能 × 2」的伤害,消耗所有充能。",
    art: "cards/orbital_cannon.png",
    effect: { custom: "orbital_cannon" },
    exhaust: false,
  },
  singularity_bomb: {
    id: "singularity_bomb",
    name: "奇点炸弹",
    cost: "X",
    type: "attack",
    target: "all_enemies",
    description: "对所有敌人造成 X×6 伤害,消耗 X×3 充能。消耗。",
    art: "cards/singularity_bomb.png",
    effect: { custom: "singularity_bomb" },
    exhaust: true,
  },
};

export function makeStartingDeck(): CardDef[] {
  const deck: CardDef[] = [];
  for (let i = 0; i < 4; i++) deck.push({ ...CARDS.laser_shot });
  for (let i = 0; i < 4; i++) deck.push({ ...CARDS.energy_shield });
  deck.push({ ...CARDS.tactical_retreat });
  deck.push({ ...CARDS.emergency_repair });
  return deck;
}

// Cards available as battle rewards (everything not in starter).
export const REWARD_POOL_IDS = [
  "med_bay",
  "blood_fuel",
  "bio_link",
  "reactor_overclock",
  "tactical_ai",
  "nano_repair",
  "data_scan",
  "weakness_analysis",
  "plasma_strike",
  "orbital_cannon",
  "singularity_bomb",
];
