import type { CardDef } from "./types";

// 61 unique cards across 4 archetypes + neutral.
export const CARDS: Record<string, CardDef> = {
  // ===== NEUTRAL (10) =====
  laser_shot: {
    id: "laser_shot",
    name: "激光射击",
    cost: 1,
    type: "attack",
    target: "enemy",
    description: "造成 6 点伤害。",
    art: "cards/laser_shot.png",
    effect: { damage: 6 },
    archetype: "neutral",
  },
  energy_shield: {
    id: "energy_shield",
    name: "能量护盾",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 5 点格挡。",
    art: "cards/energy_shield.png",
    effect: { block: 5 },
    archetype: "neutral",
  },
  tactical_retreat: {
    id: "tactical_retreat",
    name: "战术撤离",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 8 点格挡,抽 1 张牌。",
    art: "cards/tactical_retreat.png",
    effect: { block: 8, draw: 1 },
    archetype: "neutral",
  },
  emergency_repair: {
    id: "emergency_repair",
    name: "应急维修",
    cost: 0,
    type: "skill",
    target: "self",
    description: "失去 2 点 HP,获得 3 点充能。",
    art: "cards/emergency_repair.png",
    effect: { hpCost: 2, charge: 3 },
    archetype: "neutral",
  },
  weakness_analysis: {
    id: "weakness_analysis",
    name: "弱点分析",
    cost: 0,
    type: "skill",
    target: "enemy",
    description: "施加 2 层易伤。",
    art: "cards/weakness_analysis.png",
    effect: { vulnerable: 2 },
    archetype: "neutral",
  },
  data_scan: {
    id: "data_scan",
    name: "数据扫描",
    cost: 1,
    type: "skill",
    target: "self",
    description: "抽 2 张牌;若充能 ≥ 10,改为抽 3 张。",
    art: "cards/data_scan.png",
    effect: { custom: "data_scan" },
    archetype: "neutral",
  },
  tactical_ai: {
    id: "tactical_ai",
    name: "战术 AI",
    cost: 1,
    type: "power",
    target: "self",
    description: "能力。每当你获得充能时,获得 1 点格挡。",
    art: "cards/tactical_ai.png",
    effect: { custom: "tactical_ai" },
    archetype: "neutral",
  },
  nano_repair: {
    id: "nano_repair",
    name: "纳米修复",
    cost: 1,
    type: "power",
    target: "self",
    description: "能力。回合结束治疗 1 HP。",
    art: "cards/nano_repair.png",
    effect: { custom: "nano_repair" },
    archetype: "neutral",
  },
  energy_recycle: {
    id: "energy_recycle",
    name: "能量回收",
    cost: 0,
    type: "skill",
    target: "self",
    description: "抽 1 张牌。",
    art: "cards/energy_recycle.png",
    effect: { draw: 1 },
    archetype: "neutral",
  },
  overload_start: {
    id: "overload_start",
    name: "过载启动",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 2 点充能,获得 3 点格挡。",
    art: "cards/overload_start.png",
    effect: { charge: 2, block: 3 },
    archetype: "neutral",
  },

  // ===== BERSERK REACTOR (12) =====
  med_bay: {
    id: "med_bay",
    name: "医疗舱",
    cost: 1,
    type: "skill",
    target: "self",
    description: "治疗 12 点 HP,抽 1 张牌。",
    art: "cards/med_bay.png",
    effect: { heal: 12, draw: 1 },
    archetype: "berserk",
  },
  blood_fuel: {
    id: "blood_fuel",
    name: "血液燃料",
    cost: 0,
    type: "skill",
    target: "self",
    description: "失去 3 点 HP,本回合获得 1 点能量。",
    art: "cards/blood_fuel.png",
    effect: { hpCost: 3, bonusEnergy: 1 },
    archetype: "berserk",
  },
  bio_link: {
    id: "bio_link",
    name: "生命链接",
    cost: 1,
    type: "skill",
    target: "self",
    description: "失去 5 点 HP,你的下一张攻击牌伤害翻倍。",
    art: "cards/bio_link.png",
    effect: { hpCost: 5, doubleNextAttack: true },
    archetype: "berserk",
  },
  reactor_overclock: {
    id: "reactor_overclock",
    name: "反应堆超频",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。每回合开始获得 2 充能,失去 2 HP。",
    art: "cards/reactor_overclock.png",
    effect: { custom: "reactor_overclock" },
    archetype: "berserk",
  },
  plasma_strike: {
    id: "plasma_strike",
    name: "等离子斩",
    cost: 1,
    type: "attack",
    target: "enemy",
    description: "造成 8 点伤害。消耗 3 充能,则额外造成 8 点伤害。",
    art: "cards/plasma_strike.png",
    effect: { custom: "plasma_strike" },
    archetype: "berserk",
  },
  orbital_cannon: {
    id: "orbital_cannon",
    name: "轨道炮",
    cost: 3,
    type: "attack",
    target: "enemy",
    description: "造成等同于「充能 × 2」的伤害,消耗所有充能。",
    art: "cards/orbital_cannon.png",
    effect: { custom: "orbital_cannon" },
    archetype: "berserk",
  },
  singularity_bomb: {
    id: "singularity_bomb",
    name: "奇点炸弹",
    cost: "X",
    type: "attack",
    target: "all_enemies",
    description: "对所有敌人造成 X×6 伤害,消耗 X×3 充能。消耗。",
    art: "cards/singularity_bomb.png",
    effect: { custom: "singularity_bomb" },
    exhaust: true,
    archetype: "berserk",
  },
  reverse_transfusion: {
    id: "reverse_transfusion",
    name: "逆向输血",
    cost: 0,
    type: "skill",
    target: "self",
    description: "失去 2 点 HP,获得 5 点充能。",
    art: "cards/reverse_transfusion.png",
    effect: { hpCost: 2, charge: 5 },
    archetype: "berserk",
  },
  overload_discharge: {
    id: "overload_discharge",
    name: "过载放电",
    cost: 2,
    type: "attack",
    target: "all_enemies",
    description: "对所有敌人造成「当前充能/2」点伤害,消耗一半充能。",
    art: "cards/overload_discharge.png",
    effect: { custom: "overload_discharge" },
    archetype: "berserk",
  },
  doomsday_protocol: {
    id: "doomsday_protocol",
    name: "末日协议",
    cost: 3,
    type: "attack",
    target: "enemy",
    description: "造成 12 点伤害,失去 5 HP,获得 5 充能。",
    art: "cards/doomsday_protocol.png",
    effect: { damage: 12, hpCost: 5, charge: 5 },
    archetype: "berserk",
  },
  nuclear_meltdown: {
    id: "nuclear_meltdown",
    name: "核熔毁",
    cost: 3,
    type: "power",
    target: "self",
    description: "能力。每回合开始获得 3 充能,失去 3 HP。",
    art: "cards/nuclear_meltdown.png",
    effect: { custom: "nuclear_meltdown" },
    archetype: "berserk",
  },
  phoenix_protocol: {
    id: "phoenix_protocol",
    name: "凤凰协议",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。本场战斗第一次 HP < 30% 时,治疗 25 HP。",
    art: "cards/phoenix_protocol.png",
    effect: { custom: "phoenix_protocol" },
    archetype: "berserk",
  },

  // ===== AEGIS MATRIX (12) =====
  metalize: {
    id: "metalize",
    name: "金属化",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。你的格挡不会在回合结束时清零。",
    art: "cards/metalize.png",
    effect: { custom: "metalize" },
    archetype: "aegis",
  },
  bounce_field: {
    id: "bounce_field",
    name: "反弹场",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 5 格挡。下一次受到攻击时,反弹 50% 伤害。",
    art: "cards/bounce_field.png",
    effect: { block: 5, custom: "bounce_field" },
    archetype: "aegis",
  },
  magnetic_storm: {
    id: "magnetic_storm",
    name: "磁暴护盾",
    cost: 2,
    type: "skill",
    target: "self",
    description: "获得 10 格挡,对所有敌人造成 4 伤害。",
    art: "cards/magnetic_storm.png",
    effect: { block: 10, custom: "magnetic_storm" },
    archetype: "aegis",
  },
  reactive_armor: {
    id: "reactive_armor",
    name: "反应装甲",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。每次受到攻击,获得 2 格挡。",
    art: "cards/reactive_armor.png",
    effect: { custom: "reactive_armor" },
    archetype: "aegis",
  },
  energy_armor: {
    id: "energy_armor",
    name: "能量护甲",
    cost: 1,
    type: "skill",
    target: "self",
    description: "获得 4 点护甲(回合结束不清零)。",
    art: "cards/energy_armor.png",
    effect: { armor: 4 },
    archetype: "aegis",
  },
  field_charge: {
    id: "field_charge",
    name: "激发力场",
    cost: 1,
    type: "skill",
    target: "self",
    description: "下一回合开始时,获得 8 点格挡。",
    art: "cards/field_charge.png",
    effect: { custom: "field_charge" },
    archetype: "aegis",
  },
  deflection_strike: {
    id: "deflection_strike",
    name: "轨道折射",
    cost: 1,
    type: "attack",
    target: "enemy",
    description: "造成等同于「当前格挡」的伤害。",
    art: "cards/deflection_strike.png",
    effect: { custom: "deflection_strike" },
    archetype: "aegis",
  },
  charge_absorb: {
    id: "charge_absorb",
    name: "吸收充能",
    cost: 1,
    type: "power",
    target: "self",
    description: "能力。受到攻击但未破防时,获得 2 充能。",
    art: "cards/charge_absorb.png",
    effect: { custom: "charge_absorb" },
    archetype: "aegis",
  },
  overcharge_shield: {
    id: "overcharge_shield",
    name: "过载护盾",
    cost: 2,
    type: "skill",
    target: "self",
    description: "获得 12 格挡。本回合获得的充能 ×2。",
    art: "cards/overcharge_shield.png",
    effect: { block: 12, custom: "overcharge_shield" },
    archetype: "aegis",
  },
  iron_wall: {
    id: "iron_wall",
    name: "铁壁",
    cost: 0,
    type: "skill",
    target: "self",
    description: "获得 3 格挡。若你已有 ≥ 10 格挡,改为获得 6 格挡。",
    art: "cards/iron_wall.png",
    effect: { custom: "iron_wall" },
    archetype: "aegis",
  },
  resonance_barrier: {
    id: "resonance_barrier",
    name: "共振屏障",
    cost: 3,
    type: "power",
    target: "self",
    description: "能力。回合开始时若格挡 ≥ 15,抽 1 张牌。",
    art: "cards/resonance_barrier.png",
    effect: { custom: "resonance_barrier" },
    archetype: "aegis",
  },
  absolute_zero: {
    id: "absolute_zero",
    name: "绝对零度",
    cost: 3,
    type: "attack",
    target: "enemy",
    description: "施加 1 易伤。若你有 ≥ 20 格挡,造成 25 伤害。",
    art: "cards/absolute_zero.png",
    effect: { vulnerable: 1, custom: "absolute_zero" },
    archetype: "aegis",
  },

  // ===== DRONE SWARM (15) =====
  combat_drone: {
    id: "combat_drone",
    name: "战斗无人机",
    cost: 1,
    type: "skill",
    target: "self",
    description: "召唤一架战斗无人机(每回合开始造成 4 伤害)。",
    art: "cards/combat_drone.png",
    effect: { summon: "combat" },
    archetype: "drone",
  },
  guardian_drone: {
    id: "guardian_drone",
    name: "护卫无人机",
    cost: 1,
    type: "skill",
    target: "self",
    description: "召唤一架护卫无人机(每回合开始 +3 格挡)。",
    art: "cards/guardian_drone.png",
    effect: { summon: "guardian" },
    archetype: "drone",
  },
  repair_drone: {
    id: "repair_drone",
    name: "修复无人机",
    cost: 2,
    type: "skill",
    target: "self",
    description: "召唤一架修复无人机(每回合开始 +2 HP)。",
    art: "cards/repair_drone.png",
    effect: { summon: "repair" },
    archetype: "drone",
  },
  scout_drone: {
    id: "scout_drone",
    name: "侦察无人机",
    cost: 1,
    type: "skill",
    target: "self",
    description: "召唤一架侦察无人机(每回合开始抽 1 张牌)。",
    art: "cards/scout_drone.png",
    effect: { summon: "scout" },
    archetype: "drone",
  },
  swarm_protocol: {
    id: "swarm_protocol",
    name: "集群协议",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。同种无人机的效果可叠加。",
    art: "cards/swarm_protocol.png",
    effect: { custom: "swarm_protocol" },
    archetype: "drone",
  },
  drone_charge: {
    id: "drone_charge",
    name: "无人机充电",
    cost: 1,
    type: "skill",
    target: "self",
    description: "你的所有无人机立即额外行动一次。",
    art: "cards/drone_charge.png",
    effect: { custom: "drone_charge" },
    archetype: "drone",
  },
  production_line: {
    id: "production_line",
    name: "量产线",
    cost: 3,
    type: "power",
    target: "self",
    description: "能力。每回合开始召唤 1 架战斗无人机。",
    art: "cards/production_line.png",
    effect: { custom: "production_line" },
    archetype: "drone",
  },
  swarm_strike: {
    id: "swarm_strike",
    name: "机蜂涌动",
    cost: 1,
    type: "attack",
    target: "enemy",
    description: "造成 3 伤害,无人机数量 × 倍。",
    art: "cards/swarm_strike.png",
    effect: { custom: "swarm_strike" },
    archetype: "drone",
  },
  overclock_drone: {
    id: "overclock_drone",
    name: "超频无人机",
    cost: 1,
    type: "skill",
    target: "self",
    description: "你的所有无人机本回合行动效果翻倍。",
    art: "cards/overclock_drone.png",
    effect: { custom: "overclock_drone" },
    archetype: "drone",
  },
  ai_hub: {
    id: "ai_hub",
    name: "AI 中枢",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。所有无人机的行动效果 +1。",
    art: "cards/ai_hub.png",
    effect: { custom: "ai_hub" },
    archetype: "drone",
  },
  drone_recycle: {
    id: "drone_recycle",
    name: "无人机回收",
    cost: 0,
    type: "skill",
    target: "self",
    description: "消耗一架无人机,获得 5 点能量(本回合不消失)。",
    art: "cards/drone_recycle.png",
    effect: { custom: "drone_recycle" },
    archetype: "drone",
  },
  swarm_nuke: {
    id: "swarm_nuke",
    name: "机群核爆",
    cost: 3,
    type: "attack",
    target: "all_enemies",
    description: "消耗所有无人机,对所有敌人造成「数量 × 8」伤害。消耗。",
    art: "cards/swarm_nuke.png",
    effect: { custom: "swarm_nuke" },
    exhaust: true,
    archetype: "drone",
  },
  prefab_drone: {
    id: "prefab_drone",
    name: "预制无人机",
    cost: 0,
    type: "skill",
    target: "self",
    description: "获得 1 充能。下一张召唤卡 -1 费用。消耗。",
    art: "cards/prefab_drone.png",
    effect: { charge: 1, custom: "prefab_drone" },
    exhaust: true,
    archetype: "drone",
  },
  swarm_barrage: {
    id: "swarm_barrage",
    name: "机群弹幕",
    cost: 2,
    type: "attack",
    target: "enemy",
    description: "造成 4 × 战斗无人机数量 的伤害。",
    art: "cards/swarm_barrage.png",
    effect: { custom: "swarm_barrage" },
    archetype: "drone",
  },
  swarm_heart: {
    id: "swarm_heart",
    name: "机群之心",
    cost: 1,
    type: "power",
    target: "self",
    description: "能力。你的无人机不能被消耗。",
    art: "cards/swarm_heart.png",
    effect: { custom: "swarm_heart" },
    archetype: "drone",
  },

  // ===== CYBERWAR (12) =====
  hack_protocol: {
    id: "hack_protocol",
    name: "入侵协议",
    cost: 1,
    type: "skill",
    target: "enemy",
    description: "施加 2 层黑客。",
    art: "cards/hack_protocol.png",
    effect: { hack: 2 },
    archetype: "cyber",
  },
  logic_bomb: {
    id: "logic_bomb",
    name: "逻辑炸弹",
    cost: 2,
    type: "attack",
    target: "enemy",
    description: "造成 6 伤害,施加 3 黑客。",
    art: "cards/logic_bomb.png",
    effect: { damage: 6, hack: 3 },
    archetype: "cyber",
  },
  ice_breaker: {
    id: "ice_breaker",
    name: "冰墙拆除",
    cost: 0,
    type: "skill",
    target: "enemy",
    description: "施加 2 黑客,抽 1 张牌。",
    art: "cards/ice_breaker.png",
    effect: { hack: 2, draw: 1 },
    archetype: "cyber",
  },
  data_flood: {
    id: "data_flood",
    name: "数据洪流",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。每打出一张牌,获得 1 点信息流。",
    art: "cards/data_flood.png",
    effect: { custom: "data_flood" },
    archetype: "cyber",
  },
  overload_intrusion: {
    id: "overload_intrusion",
    name: "过载入侵",
    cost: 1,
    type: "skill",
    target: "enemy",
    description: "施加 1 黑客;若目标黑客 ≥ 3,改为施加 3 黑客。",
    art: "cards/overload_intrusion.png",
    effect: { custom: "overload_intrusion" },
    archetype: "cyber",
  },
  ai_infiltration: {
    id: "ai_infiltration",
    name: "AI 渗透",
    cost: 3,
    type: "skill",
    target: "enemy",
    description: "施加 5 黑客(必触发跳过下回合)。",
    art: "cards/ai_infiltration.png",
    effect: { hack: 5 },
    archetype: "cyber",
  },
  circuit_break: {
    id: "circuit_break",
    name: "回路熔断",
    cost: 1,
    type: "skill",
    target: "enemy",
    description: "施加 2 易伤,获得 1 点信息流。",
    art: "cards/circuit_break.png",
    effect: { vulnerable: 2, data: 1 },
    archetype: "cyber",
  },
  virus_deploy: {
    id: "virus_deploy",
    name: "病毒部署",
    cost: 2,
    type: "power",
    target: "self",
    description: "能力。回合结束时,所有敌人 +1 黑客。",
    art: "cards/virus_deploy.png",
    effect: { custom: "virus_deploy" },
    archetype: "cyber",
  },
  data_compile: {
    id: "data_compile",
    name: "数据汇编",
    cost: 2,
    type: "attack",
    target: "enemy",
    description: "消耗所有信息流,每点造成 2 伤害。",
    art: "cards/data_compile.png",
    effect: { custom: "data_compile" },
    archetype: "cyber",
  },
  mind_hijack: {
    id: "mind_hijack",
    name: "思维劫持",
    cost: "X",
    type: "skill",
    target: "self",
    description: "封装 X 层黑客,下一场战斗自动施加给随机敌人。消耗。",
    art: "cards/mind_hijack.png",
    effect: { custom: "mind_hijack" },
    exhaust: true,
    archetype: "cyber",
  },
  protocol_override: {
    id: "protocol_override",
    name: "协议覆写",
    cost: 2,
    type: "attack",
    target: "enemy",
    description: "造成 8 伤害。若目标有黑客层数,造成「黑客 × 3」额外伤害。",
    art: "cards/protocol_override.png",
    effect: { custom: "protocol_override" },
    archetype: "cyber",
  },
  quantum_encrypt: {
    id: "quantum_encrypt",
    name: "量子加密",
    cost: 1,
    type: "skill",
    target: "self",
    description: "你下次受到的伤害减半。",
    art: "cards/quantum_encrypt.png",
    effect: { custom: "quantum_encrypt" },
    archetype: "cyber",
  },
};

export function makeStartingDeck(): CardDef[] {
  const deck: CardDef[] = [];
  for (let i = 0; i < 4; i++) deck.push({ ...CARDS.laser_shot });
  for (let i = 0; i < 4; i++) deck.push({ ...CARDS.energy_shield });
  deck.push({ ...CARDS.tactical_retreat });
  deck.push({ ...CARDS.emergency_repair });
  return deck;
}

// Reward pool: everything not in starter, weighted by archetype.
export const REWARD_POOL_IDS = Object.keys(CARDS).filter(
  (id) =>
    id !== "laser_shot" &&
    id !== "energy_shield" &&
    id !== "tactical_retreat" &&
    id !== "emergency_repair",
);
